<?php

bs_side::set_title("Digitalt arkiv");

get_right_img("godthjem.jpg", null, "Blindern Studenterhjem - Et godt hjem for studenter", "Ved porten som leder opp mot Blindern Studenterhjem står dette skiltet. Foto: Cecilie Sæle Merkesvik");

echo '
<h1>Digitalt arkiv</h1>

<p>I 2010-2011 tok arkivar Peter Hagen på seg oppgaven med å digitalisere alle bøkene som hadde blitt produsert ved Blindern Studenterhjem opp gjennom tidene. Her er disse digitale versjonene lagt ut slik at de er til glede både for gamle og nåværende beboere, samt for personer som ønsker mer innsikt i hverdagen som har vært på Blindern Studenterhjem opp gjennom tidene.</p>
<p>Alle bøkene er i PDF-format. <span style="color: #FF0000">Merk at noen av filene er ganske store, og at det kan ta noe tid før dokumentet blir lastet inn.</span></p>

<h2>Jubileumsbøker</h2>
<p>Det er utgitt fire jubileumsbøker for Blindern Studenterhjem.</p>
<ul class="books jubbooks">
	<li><a href="http://blindern-studenterhjem.no/dokumenter/jubileumsboker/Blindern Boka 1925-1942.pdf"><img src="/graphics/jubileumsboker/Blindern Boka 1925-1942.pdf.jpg" alt="" /><span class="filedesc">Blindern Boka 1925-1942</span><span class="filesize"> (26 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/jubileumsboker/Blindern Studenterhjem 25 aar.pdf"><img src="/graphics/jubileumsboker/Blindern Studenterhjem 25 aar.pdf.jpg" alt="" /><span class="filedesc">Blindern Studenterhjem 25 år</span><span class="filesize"> (3,4 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/jubileumsboker/Blindern Studenthjem 1925-1975.pdf"><img src="/graphics/jubileumsboker/Blindern Studenthjem 1925-1975.pdf.jpg" alt="" /><span class="filedesc">Blindern Studenterhjem 1925-1975</span><span class="filesize"> (20 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/jubileumsboker/Blindern Studenthjem 1975-2000.pdf"><img src="/graphics/jubileumsboker/Blindern Studenthjem 1975-2000.pdf.jpg" alt="" /><span class="filedesc">Blindern Studenterhjem 1975-2000</span><span class="filesize"> (17 MB)</span></a></li>
</ul>

<h2>Blindernår</h2>
<p>Komplett samling frem til 2004.</p>
<ul class="books">
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1930.pdf"><img src="/graphics/blindernaar/Blindern året 1930.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1930</span><span class="filesize"> (13 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1931.pdf"><img src="/graphics/blindernaar/Blindern året 1931.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1931</span><span class="filesize"> (15 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1932.pdf"><img src="/graphics/blindernaar/Blindern året 1932.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1932</span><span class="filesize"> (2,0 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1933.pdf"><img src="/graphics/blindernaar/Blindern året 1933.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1933</span><span class="filesize"> (14 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1934.pdf"><img src="/graphics/blindernaar/Blindern året 1934.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1934</span><span class="filesize"> (23 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1935-36.pdf"><img src="/graphics/blindernaar/Blindern året 1935-36.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1935-36</span><span class="filesize"> (17 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1937.pdf"><img src="/graphics/blindernaar/Blindern året 1937.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1937</span><span class="filesize"> (23 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1938.pdf"><img src="/graphics/blindernaar/Blindern året 1938.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1938</span><span class="filesize"> (16 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1939.pdf"><img src="/graphics/blindernaar/Blindern året 1939.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1939</span><span class="filesize"> (26 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1940.pdf"><img src="/graphics/blindernaar/Blindern året 1940.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1940</span><span class="filesize"> (21 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1941.pdf"><img src="/graphics/blindernaar/Blindern året 1941.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1941</span><span class="filesize"> (6,0 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1942.pdf"><img src="/graphics/blindernaar/Blindern året 1942.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1942</span><span class="filesize"> (679 KB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1943-44.pdf"><img src="/graphics/blindernaar/Blindern året 1943-44.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1943-44</span><span class="filesize"> (5,7 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1946.pdf"><img src="/graphics/blindernaar/Blindern året 1946.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1946</span><span class="filesize"> (19 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1947.pdf"><img src="/graphics/blindernaar/Blindern året 1947.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1947</span><span class="filesize"> (15 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1948.pdf"><img src="/graphics/blindernaar/Blindern året 1948.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1948</span><span class="filesize"> (9,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1949.pdf"><img src="/graphics/blindernaar/Blindern året 1949.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1949</span><span class="filesize"> (5,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1950.pdf"><img src="/graphics/blindernaar/Blindern året 1950.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1950</span><span class="filesize"> (27 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1951.pdf"><img src="/graphics/blindernaar/Blindern året 1951.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1951</span><span class="filesize"> (18 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1952.pdf"><img src="/graphics/blindernaar/Blindern året 1952.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1952</span><span class="filesize"> (9,8 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1953.pdf"><img src="/graphics/blindernaar/Blindern året 1953.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1953</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1954.pdf"><img src="/graphics/blindernaar/Blindern året 1954.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1954</span><span class="filesize"> (8,8 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1955.pdf"><img src="/graphics/blindernaar/Blindern året 1955.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1955</span><span class="filesize"> (6,1 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1956.pdf"><img src="/graphics/blindernaar/Blindern året 1956.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1956</span><span class="filesize"> (37 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1957.pdf"><img src="/graphics/blindernaar/Blindern året 1957.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1957</span><span class="filesize"> (4,9 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1958.pdf"><img src="/graphics/blindernaar/Blindern året 1958.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1958</span><span class="filesize"> (7,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1959.pdf"><img src="/graphics/blindernaar/Blindern året 1959.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1959</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1960.pdf"><img src="/graphics/blindernaar/Blindern året 1960.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1960</span><span class="filesize"> (7,1 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1961.pdf"><img src="/graphics/blindernaar/Blindern året 1961.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1961</span><span class="filesize"> (16 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1962.pdf"><img src="/graphics/blindernaar/Blindern året 1962.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1962</span><span class="filesize"> (8,8 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1963.pdf"><img src="/graphics/blindernaar/Blindern året 1963.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1963</span><span class="filesize"> (24 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1964.pdf"><img src="/graphics/blindernaar/Blindern året 1964.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1964</span><span class="filesize"> (7,0 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1965.pdf"><img src="/graphics/blindernaar/Blindern året 1965.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1965</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1966.pdf"><img src="/graphics/blindernaar/Blindern året 1966.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1966</span><span class="filesize"> (9,7 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1967.pdf"><img src="/graphics/blindernaar/Blindern året 1967.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1967</span><span class="filesize"> (13 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1968.pdf"><img src="/graphics/blindernaar/Blindern året 1968.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1968</span><span class="filesize"> (8,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1969.pdf"><img src="/graphics/blindernaar/Blindern året 1969.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1969</span><span class="filesize"> (7,7 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1970.pdf"><img src="/graphics/blindernaar/Blindern året 1970.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1970</span><span class="filesize"> (7,5 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1971.pdf"><img src="/graphics/blindernaar/Blindern året 1971.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1971</span><span class="filesize"> (7,1 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1972.pdf"><img src="/graphics/blindernaar/Blindern året 1972.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1972</span><span class="filesize"> (12 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1973.pdf"><img src="/graphics/blindernaar/Blindern året 1973.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1973</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1974.pdf"><img src="/graphics/blindernaar/Blindern året 1974.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1974</span><span class="filesize"> (8,1 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1975.pdf"><img src="/graphics/blindernaar/Blindern året 1975.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1975</span><span class="filesize"> (14 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1976.pdf"><img src="/graphics/blindernaar/Blindern året 1976.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1976</span><span class="filesize"> (7,9 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1977.pdf"><img src="/graphics/blindernaar/Blindern året 1977.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1977</span><span class="filesize"> (12 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1978.pdf"><img src="/graphics/blindernaar/Blindern året 1978.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1978</span><span class="filesize"> (6,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1979.pdf"><img src="/graphics/blindernaar/Blindern året 1979.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1979</span><span class="filesize"> (7,3 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1980.pdf"><img src="/graphics/blindernaar/Blindern året 1980.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1980</span><span class="filesize"> (6,5 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1981.pdf"><img src="/graphics/blindernaar/Blindern året 1981.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1981</span><span class="filesize"> (5,5 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1983.pdf"><img src="/graphics/blindernaar/Blindern året 1983.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1983</span><span class="filesize"> (6,3 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1984.pdf"><img src="/graphics/blindernaar/Blindern året 1984.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1984</span><span class="filesize"> (5,6 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1985.pdf"><img src="/graphics/blindernaar/Blindern året 1985.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1985</span><span class="filesize"> (7,9 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1986.pdf"><img src="/graphics/blindernaar/Blindern året 1986.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1986</span><span class="filesize"> (5,6 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1987.pdf"><img src="/graphics/blindernaar/Blindern året 1987.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1987</span><span class="filesize"> (8,1 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1988.pdf"><img src="/graphics/blindernaar/Blindern året 1988.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1988</span><span class="filesize"> (8,5 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1989.pdf"><img src="/graphics/blindernaar/Blindern året 1989.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1989</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1990.pdf"><img src="/graphics/blindernaar/Blindern året 1990.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1990</span><span class="filesize"> (13 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1991.pdf"><img src="/graphics/blindernaar/Blindern året 1991.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1991</span><span class="filesize"> (15 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1992.pdf"><img src="/graphics/blindernaar/Blindern året 1992.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1992</span><span class="filesize"> (14 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1993.pdf"><img src="/graphics/blindernaar/Blindern året 1993.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1993</span><span class="filesize"> (11 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1994.pdf"><img src="/graphics/blindernaar/Blindern året 1994.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1994</span><span class="filesize"> (9,3 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1995.pdf"><img src="/graphics/blindernaar/Blindern året 1995.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1995</span><span class="filesize"> (8,4 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1996.pdf"><img src="/graphics/blindernaar/Blindern året 1996.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1996</span><span class="filesize"> (7,9 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1997.pdf"><img src="/graphics/blindernaar/Blindern året 1997.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1997</span><span class="filesize"> (14 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_1999.pdf"><img src="/graphics/blindernaar/Blindern året 1999.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 1999</span><span class="filesize"> (5,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_2000.pdf"><img src="/graphics/blindernaar/Blindern året 2000.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 2000</span><span class="filesize"> (12 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_2001.pdf"><img src="/graphics/blindernaar/Blindern året 2001.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 2001</span><span class="filesize"> (1,2 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_2002.pdf"><img src="/graphics/blindernaar/Blindern året 2002.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 2002</span><span class="filesize"> (20 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_2003.pdf"><img src="/graphics/blindernaar/Blindern året 2003.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 2003</span><span class="filesize"> (30 MB)</span></a></li>
	<li><a href="http://blindern-studenterhjem.no/dokumenter/blindernaar/blindernaaret_2004.pdf"><img src="/graphics/blindernaar/Blindern året 2004.pdf.jpg" alt="" /><span class="filedesc">Blindernåret 2004</span><span class="filesize"> (36 MB)</span></a></li>
</ul>';